### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by myselfhimself** [morshedalam/url-scraper-php#3]
Hello,

First, thanks for your library! I used it in a custom Drupal module, along with the fbsmp module (https://drupal.org/project/fbsmp).

Second, in `WebsiteParser->truncateText()` at line 279 I get the errors almost systematically : "Only variables should be passed by reference".

Splitting the code at that line in two solved the problem:

```
$exploded_var = explode('_____', wordwrap($text, $length, "_____", false));
$new_text = array_shift($exploded_var);
```

**Comment by morshedalam** [comment]
Thank you for using the class. 

Unable to replicate the error you raise and don't see any problem with this code snippet too but kept your changes.

It would be great if you can make necessary changes and send a pull request in future.
