### ISSUE TITLE
Undefined property: WebsiteParser::$metatags

### ISSUE THREAD

**Issue by myselfhimself** [morshedalam/url-scraper-php#4]
Hello,
with PHP 5.3, while scraping a website such as http://www.perdu.com/ I get the following error in website_parser.php:getMetaTags at line 266:

`Undefined property: WebsiteParser::$metatags`

The following replacement at line 266 removes the error:
`return $this->metatags;`
=>
`return isset($this->metatags) ? $this->metatags : array();`

Thanks for your work!
Have a nice day! :-)

**Comment by myselfhimself** [comment]
If array() gets returned in the next commit, the PHPDoc's @return tag for the method may be updated as well.

**Comment by morshedalam** [comment]
Incorporate your changes. Would be nice to have a pull request in future.
