### ISSUE TITLE
Notice: Undefined offset: 1 in WebsiteParser->getTitle() for facebook.com

### ISSUE THREAD

**Issue by myselfhimself** [morshedalam/url-scraper-php#5]
Hello,

when url parsing facebook.com and calling the WebsiteParser->getTitle() method, I get the following error:
`Notice: Undefined offset: 1 in WebsiteParser->getTitle()  (line 237 of url-scraper-php/website_parser.php)`

(line number may be unexact as I patched the WebsiteParser code earlier)

**Comment by myselfhimself** [comment]
Proposed code change:
Replace:
`private $title_expression = "/<title>(.*)<\/title>/";` website_parser.php @ line 84
With (adding attributes skipping & cases insensitivity):
`private $title_expression = "/<title[^>]*>(.*)<\/title>/i";`

To allow cases where the retrieved page's markup contains no title at all, replace
`return $match_title[1];` within WebsiteParser::getTitle() @ ~line 237
with:
`return isset($match_title[1]) ? $match_title[1] : '';`

**Comment by myselfhimself** [comment]
Actually almost all private `$.._expression` in the WebsiteParser class would help having case insentitivity...

**Comment by morshedalam** [comment]
Not sure how you generates the error, it can happen for empty grabbed content though it shouldn't happen. Made changes to check undefined error.
